### ISSUE TITLE
Please log the network error information for better debug

### ISSUE THREAD

**Issue by shokakucarrier** [woai3c/node-blog#2]
There is no log when hit a network error, and solve the issue is hard, please at lease have some output to console for tracking.

**Comment by woai3c** [comment]
Hello, thank you for your advice. I'll consider adding error logs. But I'm not familiar with nginx and docker. After all, this is my project to learn node, so I have to study how to add error logs.

I see that you have FORK for this project, so I suggest you make any changes according to your wishes.
