### ISSUE TITLE
似乎不能运行

### ISSUE THREAD

**Issue by LeedaCode** [woai3c/node-blog#3]
我尝试运行 但是都失败了

**Comment by woai3c** [comment]
报错信息是什么，有按以下步骤运行吗
1.下载数据库
2.克隆项目
3.下载依赖
4.打开数据库
5.运行项目

**Comment by LeedaCode** [comment]
按照步骤做好了，尝试运行时 
使用 npm run dev
发生如下图错误，你能帮我定位一下问题吗？是vue的模块没有安装好吗？
http://47.99.120.179/img/images/2019/08/30/X6YTM1BOUNNKE0XOY5I.png

**Comment by woai3c** [comment]
加下我QQ 411020382 你这是有模块没找到

**Comment by woai3c** [comment]
你的是 Linux 系统，可能是大小写的问题，请你把 `node-blog/src/view/index` 路径下的 `index.vue` 文件改为 `Index.vue`
